n1 = float(input("Digite a primeira nota: "))
print()
n2 = float(input("Digite a segunda nota: "))
print()
n3 = float(input("Digite a terceira nota: "))
print()
n4 = float(input("Digite a quarta  nota: "))
print()
media = (n1+n2+n3+n4)/4
print("A média aritmética é",media)
